server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema?serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    #自动|创建|验证更新表结构
    hibernate:
      ddl-auto: update
    #设置数据库引擎为InnoDBD
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    #打印sql日志方便调试
    show-sql: true